# Generated by Django 6.0.8 on 2026-08-06 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên danh mục"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Thời điểm xóa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tạo bởi",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cập nhật bởi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh mục",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã sản phẩm"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên sản phẩm")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Cái"),
                            ("item", "Chiếc"),
                            ("box", "Hộp"),
                            ("pack", "Gói"),
                            ("bottle", "Chai"),
                            ("can", "Lon"),
                            ("kg", "Kilogram (kg)"),
                            ("g", "Gram (g)"),
                            ("l", "Lít (l)"),
                            ("ml", "Mililit (ml)"),
                        ],
                        default="piece",
                        max_length=50,
                        verbose_name="Đơn vị tính",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mô tả sản phẩm"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="products/",
                        verbose_name="Hình ảnh sản phẩm",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang kinh doanh"),
                            ("inactive", "Ngừng kinh doanh"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Thời điểm xóa",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Giá nhập",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Giá bán",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="product.category",
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tạo bởi",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cập nhật bởi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Sản phẩm",
                "ordering": ["-id"],
            },
        ),
    ]
