# Generated by Django 6.0.8 on 2026-08-09 13:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def initialize_existing_product_balances(apps, schema_editor):
    """Create a zero-balance Inventory for Products predating this app."""
    Product = apps.get_model("product", "Product")
    Inventory = apps.get_model("inventory", "Inventory")
    Inventory.objects.bulk_create(
        [
            Inventory(
                product_id=product.id,
                created_by_id=product.created_by_id,
                updated_by_id=product.updated_by_id,
            )
            for product in Product.objects.all()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0002_alter_product_options_category_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Số lượng tồn",
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("10.000"),
                        max_digits=14,
                        verbose_name="Ngưỡng tồn thấp",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_record",
                        to="product.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tồn kho",
                "verbose_name_plural": "Tồn kho",
                "db_table": "inventory_inventory",
                "ordering": ["product__sku"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("inbound", "Nhập kho"),
                            ("outbound", "Xuất kho"),
                            ("adjustment", "Điều chỉnh"),
                        ],
                        max_length=20,
                        verbose_name="Loại giao dịch",
                    ),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        verbose_name="Số lượng thay đổi",
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        verbose_name="Tồn trước giao dịch",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=14,
                        verbose_name="Tồn sau giao dịch",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Mã tham chiếu",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="Ghi chú"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.inventory",
                        verbose_name="Tồn kho",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biến động kho",
                "verbose_name_plural": "Biến động kho",
                "db_table": "inventory_stock_movement",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["quantity"], name="idx_inventory_quantity"),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)),
                name="inventory_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("low_stock_threshold__gte", 0)),
                name="inventory_threshold_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["movement_type"], name="idx_movement_type"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["created_at"], name="idx_movement_created"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_delta", 0), _negated=True),
                name="movement_delta_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("balance_before__gte", 0), ("balance_after__gte", 0)
                ),
                name="movement_balances_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("movement_type", "inbound"), ("quantity_delta__gt", 0)),
                    models.Q(("movement_type", "outbound"), ("quantity_delta__lt", 0)),
                    models.Q(
                        ("movement_type", "adjustment"),
                        models.Q(("quantity_delta", 0), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="movement_delta_matches_type",
            ),
        ),
        migrations.RunPython(
            initialize_existing_product_balances,
            migrations.RunPython.noop,
        ),
    ]
